/*
 * This file is generated by jOOQ.
*/
package com.acme.moneytransfer.infrastructure.persistence.projection.jooq;


import com.acme.moneytransfer.infrastructure.persistence.projection.jooq.tables.MoneyTransfer;
import com.acme.moneytransfer.infrastructure.persistence.projection.jooq.tables.records.MoneyTransferRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>PUBLIC</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MoneyTransferRecord> CONSTRAINT_7 = UniqueKeys0.CONSTRAINT_7;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<MoneyTransferRecord> CONSTRAINT_7 = Internal.createUniqueKey(MoneyTransfer.MONEY_TRANSFER, "CONSTRAINT_7", MoneyTransfer.MONEY_TRANSFER.ID);
    }
}
