/*
 * This file is generated by jOOQ.
*/
package com.acme.moneytransfer.infrastructure.persistence.projection.jooq;


import com.acme.moneytransfer.infrastructure.persistence.projection.jooq.tables.MoneyTransfer;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.MONEY_TRANSFER</code>.
     */
    public static final MoneyTransfer MONEY_TRANSFER = com.acme.moneytransfer.infrastructure.persistence.projection.jooq.tables.MoneyTransfer.MONEY_TRANSFER;
}
