/*
 * This file is generated by jOOQ.
*/
package com.acme.moneytransfer.infrastructure.persistence.projection.jooq.tables.records;


import com.acme.moneytransfer.infrastructure.persistence.projection.jooq.tables.MoneyTransfer;

import java.math.BigDecimal;
import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MoneyTransferRecord extends UpdatableRecordImpl<MoneyTransferRecord> implements Record14<String, String, BigDecimal, String, Timestamp, String, String, String, String, String, String, Date, String, Integer> {

    private static final long serialVersionUID = -1927209350;

    /**
     * Setter for <code>PUBLIC.MONEY_TRANSFER.ID</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>PUBLIC.MONEY_TRANSFER.ID</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>PUBLIC.MONEY_TRANSFER.ACCOUNT_ID</code>.
     */
    public void setAccountId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>PUBLIC.MONEY_TRANSFER.ACCOUNT_ID</code>.
     */
    public String getAccountId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>PUBLIC.MONEY_TRANSFER.AMOUNT</code>.
     */
    public void setAmount(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>PUBLIC.MONEY_TRANSFER.AMOUNT</code>.
     */
    public BigDecimal getAmount() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>PUBLIC.MONEY_TRANSFER.CURRENCY</code>.
     */
    public void setCurrency(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>PUBLIC.MONEY_TRANSFER.CURRENCY</code>.
     */
    public String getCurrency() {
        return (String) get(3);
    }

    /**
     * Setter for <code>PUBLIC.MONEY_TRANSFER.LAST_STATUS_CHANGE_DATE</code>.
     */
    public void setLastStatusChangeDate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>PUBLIC.MONEY_TRANSFER.LAST_STATUS_CHANGE_DATE</code>.
     */
    public Timestamp getLastStatusChangeDate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>PUBLIC.MONEY_TRANSFER.STATUS</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>PUBLIC.MONEY_TRANSFER.STATUS</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    /**
     * Setter for <code>PUBLIC.MONEY_TRANSFER.NUMBER</code>.
     */
    public void setNumber(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>PUBLIC.MONEY_TRANSFER.NUMBER</code>.
     */
    public String getNumber() {
        return (String) get(6);
    }

    /**
     * Setter for <code>PUBLIC.MONEY_TRANSFER.ADDRESS_LINE</code>.
     */
    public void setAddressLine(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>PUBLIC.MONEY_TRANSFER.ADDRESS_LINE</code>.
     */
    public String getAddressLine() {
        return (String) get(7);
    }

    /**
     * Setter for <code>PUBLIC.MONEY_TRANSFER.CITY</code>.
     */
    public void setCity(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>PUBLIC.MONEY_TRANSFER.CITY</code>.
     */
    public String getCity() {
        return (String) get(8);
    }

    /**
     * Setter for <code>PUBLIC.MONEY_TRANSFER.ZIP_CODE</code>.
     */
    public void setZipCode(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>PUBLIC.MONEY_TRANSFER.ZIP_CODE</code>.
     */
    public String getZipCode() {
        return (String) get(9);
    }

    /**
     * Setter for <code>PUBLIC.MONEY_TRANSFER.RECIPIENT_NAME</code>.
     */
    public void setRecipientName(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>PUBLIC.MONEY_TRANSFER.RECIPIENT_NAME</code>.
     */
    public String getRecipientName() {
        return (String) get(10);
    }

    /**
     * Setter for <code>PUBLIC.MONEY_TRANSFER.TRANSFER_DATE</code>.
     */
    public void setTransferDate(Date value) {
        set(11, value);
    }

    /**
     * Getter for <code>PUBLIC.MONEY_TRANSFER.TRANSFER_DATE</code>.
     */
    public Date getTransferDate() {
        return (Date) get(11);
    }

    /**
     * Setter for <code>PUBLIC.MONEY_TRANSFER.TRANSFER_DESCRIPTION</code>.
     */
    public void setTransferDescription(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>PUBLIC.MONEY_TRANSFER.TRANSFER_DESCRIPTION</code>.
     */
    public String getTransferDescription() {
        return (String) get(12);
    }

    /**
     * Setter for <code>PUBLIC.MONEY_TRANSFER.VERSION</code>.
     */
    public void setVersion(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>PUBLIC.MONEY_TRANSFER.VERSION</code>.
     */
    public Integer getVersion() {
        return (Integer) get(13);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record14 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, BigDecimal, String, Timestamp, String, String, String, String, String, String, Date, String, Integer> fieldsRow() {
        return (Row14) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row14<String, String, BigDecimal, String, Timestamp, String, String, String, String, String, String, Date, String, Integer> valuesRow() {
        return (Row14) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return MoneyTransfer.MONEY_TRANSFER.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MoneyTransfer.MONEY_TRANSFER.ACCOUNT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return MoneyTransfer.MONEY_TRANSFER.AMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return MoneyTransfer.MONEY_TRANSFER.CURRENCY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return MoneyTransfer.MONEY_TRANSFER.LAST_STATUS_CHANGE_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return MoneyTransfer.MONEY_TRANSFER.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return MoneyTransfer.MONEY_TRANSFER.NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return MoneyTransfer.MONEY_TRANSFER.ADDRESS_LINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return MoneyTransfer.MONEY_TRANSFER.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return MoneyTransfer.MONEY_TRANSFER.ZIP_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return MoneyTransfer.MONEY_TRANSFER.RECIPIENT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field12() {
        return MoneyTransfer.MONEY_TRANSFER.TRANSFER_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return MoneyTransfer.MONEY_TRANSFER.TRANSFER_DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return MoneyTransfer.MONEY_TRANSFER.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getLastStatusChangeDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getAddressLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getRecipientName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component12() {
        return getTransferDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getTransferDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAccountId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getAmount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getLastStatusChangeDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getAddressLine();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getZipCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getRecipientName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value12() {
        return getTransferDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getTransferDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoneyTransferRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoneyTransferRecord value2(String value) {
        setAccountId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoneyTransferRecord value3(BigDecimal value) {
        setAmount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoneyTransferRecord value4(String value) {
        setCurrency(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoneyTransferRecord value5(Timestamp value) {
        setLastStatusChangeDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoneyTransferRecord value6(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoneyTransferRecord value7(String value) {
        setNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoneyTransferRecord value8(String value) {
        setAddressLine(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoneyTransferRecord value9(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoneyTransferRecord value10(String value) {
        setZipCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoneyTransferRecord value11(String value) {
        setRecipientName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoneyTransferRecord value12(Date value) {
        setTransferDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoneyTransferRecord value13(String value) {
        setTransferDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoneyTransferRecord value14(Integer value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MoneyTransferRecord values(String value1, String value2, BigDecimal value3, String value4, Timestamp value5, String value6, String value7, String value8, String value9, String value10, String value11, Date value12, String value13, Integer value14) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MoneyTransferRecord
     */
    public MoneyTransferRecord() {
        super(MoneyTransfer.MONEY_TRANSFER);
    }

    /**
     * Create a detached, initialised MoneyTransferRecord
     */
    public MoneyTransferRecord(String id, String accountId, BigDecimal amount, String currency, Timestamp lastStatusChangeDate, String status, String number, String addressLine, String city, String zipCode, String recipientName, Date transferDate, String transferDescription, Integer version) {
        super(MoneyTransfer.MONEY_TRANSFER);

        set(0, id);
        set(1, accountId);
        set(2, amount);
        set(3, currency);
        set(4, lastStatusChangeDate);
        set(5, status);
        set(6, number);
        set(7, addressLine);
        set(8, city);
        set(9, zipCode);
        set(10, recipientName);
        set(11, transferDate);
        set(12, transferDescription);
        set(13, version);
    }
}
